sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - "3.4"

before_install:
  - ./.travis/install-dependencies.sh
  - docker build -t bionitio-python .

script:
  - ./functional_tests/bionitio-test.sh -p bionitio -d functional_tests/test_data
  - docker run --entrypoint /bionitio/functional_tests/bionitio-test.sh bionitio -p bionitio -d /bionitio/functional_tests/test_data
  - ./.travis/unit-test.sh
  - docker run --entrypoint /bionitio/.travis/unit-test.sh bionitio

