sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - "3.4"

before_install:
  - ./.travis/install-dependencies.sh
  - docker build -t bionitio-python .

script:
  # Functional tests
  - ./functional_tests/bionitio-test.sh -p bionitio -d functional_tests/test_data
  # Unit tests
  - ./.travis/unit-test.sh

  # Both of these same tests, in Docker
  - docker run --entrypoint /bionitio/.travis/unit-test.sh bionitio-python
  - docker run --entrypoint /bionitio/functional_tests/bionitio-test.sh bionitio-python -p bionitio -d /bionitio/functional_tests/test_data

  # CWL definition test
  - cwltool bionitio.cwl --fasta_file /bionitio/functional_tests/test_data/two_sequence.fasta
